import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { getPublicBrand } from '@/lib/brands'
import { StyleBriefDisplay } from '@/components/brand/StyleBriefDisplay'

interface Params { params: { id: string } }

export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const brand = await getPublicBrand(params.id)
  if (!brand) return { title: 'Brand not found' }
  return {
    title: `${brand.name} — brand kit made with BrandKit`,
    description: brand.brandResult.styleBrief.recommendedStyle,
    openGraph: {
      title: `${brand.name}`,
      description: `A brand kit generated by BrandKit — ${brand.brandResult.styleBrief.recommendedStyle}`,
      type: 'website',
    },
  }
}

export default async function SharedBrandPage({ params }: Params) {
  const brand = await getPublicBrand(params.id)
  if (!brand) notFound()

  return (
    <div className="pt-4 pb-12">
      <div className="mb-6">
        <p className="text-xs text-zinc-500 uppercase tracking-widest mb-1">Shared brand</p>
        <h1 className="text-3xl font-bold tracking-tight text-white">{brand.name}</h1>
      </div>

      <div className="rounded-2xl bg-white p-8 mb-6 flex items-center justify-center">
        <img src={brand.selectedLogoUrl} alt={brand.name} className="max-h-32 object-contain" />
      </div>

      <StyleBriefDisplay brief={brand.brandResult.styleBrief} />

      {brand.mockupUrls.length > 0 && (
        <section className="mt-8">
          <p className="text-xs text-zinc-500 uppercase tracking-widest mb-3">Mockups</p>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
            {brand.mockupUrls.map((m) => (
              <div
                key={m.templateId}
                className="aspect-square rounded-xl overflow-hidden bg-zinc-900 border border-zinc-800"
              >
                <img src={m.url} alt={m.templateId} className="w-full h-full object-contain" />
              </div>
            ))}
          </div>
        </section>
      )}

      <div className="mt-10 pt-6 border-t border-zinc-800 text-center">
        <p className="text-sm text-zinc-400 mb-3">Want your own?</p>
        <a
          href="/"
          className="inline-flex items-center justify-center bg-white text-zinc-950 px-5 py-2.5 rounded-md font-medium hover:bg-zinc-200"
        >
          Create your brand with BrandKit →
        </a>
      </div>
    </div>
  )
}
