import Hero from '@/components/landing/Hero'
import { ScrollReveal } from '@/components/ui/ScrollReveal'

const steps = [
  {
    image: '/landing/step-input.png',
    title: '1. Tell us your brand',
    body: '30-second form — industry, audience, tone.',
  },
  {
    image: '/landing/step-generate.png',
    title: '2. AI generates everything',
    body: 'Naming options, brand brief, 3 logos, 9 mockups.',
  },
  {
    image: '/landing/step-download.png',
    title: '3. Download your kit',
    body: 'PNG / SVG / PDF / ZIP — yours to use.',
  },
]

const features = [
  { title: 'AI brand brief', body: 'Style direction, color palette, typography.' },
  { title: '3 logo variants', body: 'Generated by Imagen 4.' },
  { title: '9 product mockups', body: 'Business card, app icon, social post, envelopes, letterhead, t-shirt, mug, pen.' },
  { title: 'Vector SVG logo', body: 'Scalable, ready for any size.' },
  { title: '1-page brand guide PDF', body: 'Share with your team or designers.' },
  { title: 'Asset Pack ZIP', body: 'Everything bundled in one download.' },
]

const plans = [
  { name: 'Free', price: '$0' },
  { name: 'Essentials', price: '$29' },
  { name: 'Pro', price: '$149' },
]

const faqs = [
  {
    q: 'How long does generating take?',
    a: 'About 1-2 minutes end to end.',
  },
  {
    q: 'Can I use the assets commercially?',
    a: 'Yes — you own the output, full commercial use.',
  },
  {
    q: "What's \"designer-polished\"?",
    a: 'Our Pro tier — a real designer hand-refines your AI-generated logo (vector cleanup, kerning, color variants). Delivered in 2-3 business days.',
  },
  {
    q: 'Is my email shared with anyone?',
    a: 'No. We only use it to notify you when paid plans launch.',
  },
]

export default function Home() {
  return (
    <div className="space-y-20 md:space-y-28 pb-16">
      <Hero />

      <ScrollReveal>
      <section>
        <h2 className="text-2xl md:text-3xl font-semibold text-white mb-8">How it works</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {steps.map((s) => (
            <div key={s.title}>
              <div className="aspect-square bg-black overflow-hidden rounded-lg">
                <img
                  src={s.image}
                  alt=""
                  aria-hidden
                  className="w-full h-full object-cover"
                />
              </div>
              <h3 className="mt-4 text-base font-semibold text-white">{s.title}</h3>
              <p className="mt-1 text-sm text-zinc-400">{s.body}</p>
            </div>
          ))}
        </div>
      </section>
      </ScrollReveal>

      <ScrollReveal>
      <section>
        <h2 className="text-2xl md:text-3xl font-semibold text-white mb-8">What you get</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {features.map((f) => (
            <div key={f.title} className="rounded-lg border border-zinc-800 p-5 bg-zinc-900/40">
              <h3 className="text-base font-semibold text-white">{f.title}</h3>
              <p className="mt-2 text-sm text-zinc-400">{f.body}</p>
            </div>
          ))}
        </div>
      </section>
      </ScrollReveal>

      <ScrollReveal>
      <section>
        <h2 className="text-2xl md:text-3xl font-semibold text-white mb-8">Pricing</h2>
        <div className="grid grid-cols-3 gap-3">
          {plans.map((p) => (
            <div key={p.name} className="rounded-lg border border-zinc-800 p-4 text-center bg-zinc-900/40">
              <div className="text-sm text-zinc-400">{p.name}</div>
              <div className="mt-1 text-xl md:text-2xl font-semibold text-white">{p.price}</div>
            </div>
          ))}
        </div>
        <div className="mt-4">
          <a href="/pricing" className="text-sm text-zinc-300 hover:text-white">
            See full pricing →
          </a>
        </div>
      </section>
      </ScrollReveal>

      <ScrollReveal>
      <section>
        <h2 className="text-2xl md:text-3xl font-semibold text-white mb-8">FAQ</h2>
        <div className="space-y-3">
          {faqs.map((f) => (
            <details key={f.q} className="rounded-lg border border-zinc-800 p-4 bg-zinc-900/40 group">
              <summary className="cursor-pointer text-sm md:text-base font-medium text-white list-none flex items-center justify-between">
                <span>{f.q}</span>
                <span className="text-zinc-500 group-open:rotate-45 transition-transform">+</span>
              </summary>
              <p className="mt-3 text-sm text-zinc-400">{f.a}</p>
            </details>
          ))}
        </div>
      </section>
      </ScrollReveal>

      <footer className="pt-8 border-t border-zinc-800 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-zinc-500">
        <div className="flex gap-4">
          <a href="/pricing" className="hover:text-white">Pricing</a>
          <a href="/sign-in" className="hover:text-white">Sign in</a>
          <a href="mailto:we.lusters@gmail.com" className="hover:text-white">Contact</a>
        </div>
        <div>© 2026 BrandKit</div>
      </footer>
    </div>
  )
}
