import PDFDocument from 'pdfkit'
import sharp from 'sharp'
import type { BrandResult } from './types'

interface BuildArgs {
  brandName: string
  result: BrandResult
  logoPng: Buffer
  mockupPngs: Buffer[] // up to 3; others ignored
}

export async function buildBrandGuidePDF(args: BuildArgs): Promise<Buffer> {
  // Resize mockup thumbnails to ~240px wide so PDF stays small
  const thumbs = await Promise.all(
    args.mockupPngs.slice(0, 3).map((buf) =>
      sharp(buf).resize(240, 240, { fit: 'inside' }).png().toBuffer()
    )
  )

  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 40 })
    const chunks: Buffer[] = []
    doc.on('data', (c) => chunks.push(c as Buffer))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const { recommendedStyle, colorPalette, typography } = args.result.styleBrief
    const date = new Date().toISOString().slice(0, 10)

    // Header
    doc.fontSize(32).fillColor('#000').text(args.brandName, { align: 'left' })
    doc.fontSize(10).fillColor('#666').text(`Brand Guide · ${date}`)
    doc.moveDown(1)

    // Logo — centered, up to 200pt height
    doc.image(args.logoPng, {
      fit: [380, 200],
      align: 'center',
    })
    doc.moveDown(1.5)

    // Color palette
    doc.fontSize(12).fillColor('#000').text('Color Palette')
    doc.moveDown(0.3)
    let xCursor = 40
    const yPalette = doc.y
    colorPalette.forEach((hex) => {
      doc.rect(xCursor, yPalette, 60, 60).fillAndStroke(hex, '#e5e5e5')
      doc.fontSize(9).fillColor('#666').text(hex, xCursor, yPalette + 65, { width: 60, align: 'center' })
      xCursor += 80
    })
    doc.y = yPalette + 90
    doc.moveDown(0.5)

    // Typography
    doc.fontSize(12).fillColor('#000').text('Typography')
    doc.moveDown(0.3)
    typography.forEach((t, i) => {
      doc.fontSize(10).fillColor('#333').text(`${i === 0 ? 'Primary:   ' : 'Secondary: '}${t}`)
    })
    doc.moveDown(0.8)

    // Style brief
    doc.fontSize(12).fillColor('#000').text('Style')
    doc.moveDown(0.3)
    doc.fontSize(10).fillColor('#333').text(recommendedStyle, { width: 520 })
    doc.moveDown(0.8)

    // Mockup thumbnails
    if (thumbs.length > 0) {
      doc.fontSize(12).fillColor('#000').text('Mockups')
      doc.moveDown(0.3)
      let x = 40
      const yMock = doc.y
      thumbs.forEach((thumb) => {
        doc.image(thumb, x, yMock, { fit: [150, 150] })
        x += 170
      })
      doc.y = yMock + 160
    }

    // Footer
    doc.fontSize(8).fillColor('#999').text('Generated by Kiln', 40, 800)

    doc.end()
  })
}
