import { ScrollReveal } from '@/components/ui/ScrollReveal'

const steps = [
  { title: '1. Tell us your brand', body: '30-second form — industry, audience, tone.' },
  { title: '2. AI generates everything', body: 'Naming options, brand brief, 3 logos, 9 mockups.' },
  { title: '3. Download your kit', body: 'PNG / SVG / PDF / ZIP — yours to use.' },
]

const features = [
  { title: 'AI brand brief', body: 'Style direction, color palette, typography.' },
  { title: '3 logo variants', body: 'Generated by Imagen 4 or typography-first.' },
  { title: '9 product mockups', body: 'Business card, app icon, social post, and more.' },
  { title: 'Vector SVG logo', body: 'Scalable, ready for any size.' },
  { title: '1-page brand guide PDF', body: 'Share with your team or designers.' },
  { title: 'Asset Pack ZIP', body: 'Everything bundled in one download.' },
]

const faqs = [
  { q: 'How long does generating take?', a: 'About 1-2 minutes end to end.' },
  { q: 'Can I use the assets commercially?', a: 'Yes — you own the output, full commercial use.' },
  { q: "What's \"designer-polished\"?", a: 'Our Pro tier — a real designer hand-refines your AI-generated logo. Delivered in 2-3 business days.' },
  { q: 'Is my email shared with anyone?', a: 'No. We only use it to notify you when paid plans launch.' },
]

export default function CompanyPage() {
  return (
    <div className="space-y-16 pb-16">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-white mb-2">About Kiln</h1>
        <p className="text-zinc-400 text-base">AI-powered brand identity, from company info to a complete kit in minutes.</p>
      </div>

      <ScrollReveal>
        <section>
          <h2 className="text-xl font-semibold text-white mb-6">How it works</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {steps.map((s) => (
              <div key={s.title} className="rounded-2xl border border-zinc-800/60 bg-zinc-900/30 p-5 card-elevated">
                <h3 className="text-sm font-semibold text-white">{s.title}</h3>
                <p className="mt-1 text-xs text-zinc-400">{s.body}</p>
              </div>
            ))}
          </div>
        </section>
      </ScrollReveal>

      <ScrollReveal>
        <section>
          <h2 className="text-xl font-semibold text-white mb-6">What you get</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {features.map((f) => (
              <div key={f.title} className="rounded-2xl border border-zinc-800/60 bg-zinc-900/30 p-5 card-elevated">
                <h3 className="text-sm font-semibold text-white">{f.title}</h3>
                <p className="mt-1 text-xs text-zinc-400">{f.body}</p>
              </div>
            ))}
          </div>
        </section>
      </ScrollReveal>

      <ScrollReveal>
        <section>
          <h2 className="text-xl font-semibold text-white mb-6">FAQ</h2>
          <div className="space-y-2">
            {faqs.map((f) => (
              <details key={f.q} className="rounded-2xl border border-zinc-800/60 bg-zinc-900/30 p-4 card-elevated group">
                <summary className="cursor-pointer text-sm font-medium text-white list-none flex items-center justify-between">
                  <span>{f.q}</span>
                  <span className="text-zinc-500 group-open:rotate-45 transition-transform">+</span>
                </summary>
                <p className="mt-3 text-sm text-zinc-400">{f.a}</p>
              </details>
            ))}
          </div>
        </section>
      </ScrollReveal>

      <footer className="pt-8 border-t border-zinc-800 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-zinc-500">
        <div className="flex gap-4 flex-wrap">
          <a href="/pricing" className="hover:text-white transition-colors">Pricing</a>
          <a href="/sign-in" className="hover:text-white transition-colors">Sign in</a>
          <a href="/privacy" className="hover:text-white transition-colors">Privacy</a>
          <a href="/terms" className="hover:text-white transition-colors">Terms</a>
          <a href="mailto:we.lusters@gmail.com" className="hover:text-white transition-colors">Contact</a>
        </div>
        <div>© 2026 Kiln</div>
      </footer>
    </div>
  )
}
